[application]
name = "cyrup"
title = "Cyrup Chat"
description = "Modern chat application with AI integration"

default_platform = "desktop"

out_dir = "dist"
asset_dir = "assets"
public_dir = ""

[web.app]

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[bundle]
identifier = "com.cyrup.chat"
publisher = "Cyrup AI"
category = "SocialNetworking"
short_description = "AI-powered chat application"
long_description = "Cyrup Chat is a modern chat application with integrated AI capabilities."

[bundle.macos]
minimum_system_version = "10.13"
